title: "Cards"
description: |
   The cards work together in grids and can be combined with buttons and images.
patterns:
  bestsellers-card:
    title: "Best Sellers Card"
    description: |
      The best sellers card is to be used on the home page. It is a card used to attract the user to the products.
    width: "12em"
product-detail-card:
  title: "Product Detail Card"
  description: |
    The product detail card is used for when the user is looking for more descriptive information about the product, and leads the user to directly purchase the product.
  width: "12em"
  product-card:
    title: "Product Card"
    description: |
       The product card is to be used on the products list page, showing all of the available products in order.
