title: "Navigation"
description: |
   A navigation is an essential component to a website since it allows users to instantly access the menu and easily find what they want on your site.
patterns:
  breadcrumbs:
    title: "Breadcrumbs"
    description: |
      Breadcrumbs navigation is to be used in a page with multiple sections to further the into, which guides the users through the website.
    width: "12em"
  footer-social-icons:
    title: "Footer"
    description: |
      This navogation is to be used at the bottom of every page, and allows the user to be brought to the desired social link.
