title: "Banners"
description: |
  The banners are used to showcase the websites most important features. Banners can also be combined with buttons, images, and the header.
patterns:
  call-to-action-banner:
    title: "Call To Action"
    description: |
      A call to action banner is to be used on the home page. The matching button must be placed on this banner, bring the user to the linked page.
    width: "12em"
