title: "Banners"
description: |
  The banners are used to showcase the websites most important features. Banners can also be combined with buttons and images.
patterns:
  banner:
    title: "Main Banner"
    description: |
      A call to action banner is to be used on the home page. The matching button must be placed on this banner, bringing the user to the linked page.
